source 'http://rubygems.org'
source 'http://gems.github.com'

gem 'rails', '3.0.3'

# Deploy with Capistrano
gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
#gem 'ruby-debug'
#gem 'ruby-debug19'

# Bundle the extra gems:
gem 'git-deploy'
gem 'rack'
gem 'aasm', '2.2.0'
gem 'i18n', '0.5.0'
gem 'gemcutter'
gem 'mysql2'
gem 'faker'
gem 'geokit'
gem 'fastercsv', :platforms => 'ruby_18'
gem 'json'
gem 'eventmachine'
gem 'contacts'
gem 'domainatrix'
gem 'faker'
gem 'rest-open-uri'
gem 'hpricot'
gem 'configatron'
gem 'acts_as_commentable'
gem 'acts_as_favorite'
gem 'ajaxful_rating'
gem 'juggernaut'
gem 'activerecord', '>= 3.0.3'
gem 'riddle', '>= 1.2.1'
gem "paperclip", "~> 2.3"
gem 'acts-as-taggable-on'
gem 'ruby-mp3info'
gem 'ts-delayed-delta', :require => 'thinking_sphinx/deltas/delayed_delta'
gem 'delayed_job'
gem 'will_paginate', '~> 3.0.beta'
gem 'aws-s3'
gem 'jquery-rails', '>= 0.2.6'
gem 'chronic'
gem 'packet'
gem 'backgroundrb-rails3', :require => 'backgroundrb'
gem 'validates_timeliness', '~> 3.0.2'
gem 'rubycas-client'
gem 'simple_captcha', :git => 'git://github.com/galetahub/simple-captcha.git'
gem 'rubycas-client-rails', :path => 'vendor/plugins/rubycas-client-rails'
gem "exception_notification", :git => "git://github.com/rails/exception_notification.git", :require => "exception_notifier"
gem "aws-ses", :require => 'aws/ses'
gem 'backup-task'
gem 'whenever', :require => false
gem 'jammit'
gem 'sunspot_rails', '~> 1.2.1'
gem 'truncate_html'
gem 'sunspot_index_queue'
gem 'daemons-mikehale'
gem 'sunspot_plus'