--- 
javascripts: 
- application:
  - application
  - jquery
  - jquery-ui
  - jquery-ui-datepicker
  - jrails
  - jquery-mcdropdown
  - thickbox
  - jquery-validate
  - vtip-min
- student_lounge:
  - application
  - jquery
  - jquery-ui
  - jquery-ui-datepicker
  - jrails
  - jquery-mcdropdown
  - thickbox
  - jquery-validate
  - vtip-min
- admin:
  - application
  - jquery
  - jquery-ui
  - jquery-ui-datepicker
  - jrails
  - jquery-mcdropdown
  - thickbox
  - jquery-validate
  - vtip-min
stylesheets: 
- application:
  - main
  - post
  - jquery-ui
  - jquery-ui-theme
  - jquery-ui-datepicker
  - jquery-mcdropdown
  - thickbox
  - pagination
  - validation
  - flash
  - vtip
- student_lounge:
  - main
  - student_lounge
  - jquery-ui
  - jquery-ui-theme
  - jquery-ui-datepicker
  - jquery-mcdropdown
  - thickbox
  - pagination
  - validation
  - flash
  - vtip
- admin:
  - main