package_assets: of
embed_assets: of
compress_assets: of
allow_debugging: on

javascripts:
  base:
    - public/javascripts/jquery.js
    - public/javascripts/rails.js
    - public/javascripts/app.js
    - public/javascripts/swfobject.js
    - public/javascripts/jquery-ui.js
    - public/javascripts/jquery.mcdropdown.js
    - public/javascripts/jquery.bgiframe.js
    - public/javascripts/jquery-auto-suggest.js
    - public/javascripts/jquery-counter.js
    - public/javascripts/jquery-multiselect.js
    - public/javascripts/jquery-wysiwyg.js
    - public/javascripts/jquery-swfobject.js
    - public/javascripts/thickbox.js
    - public/javascripts/vtip.js
    - public/javascripts/json.js
    - public/javascripts/jquery-opacityrollover.js
    - public/javascripts/jquery.gmap.js
    - public/javascripts/checkboxmenu.js
    - public/javascripts/drplayer.js
    - public/javascripts/jquery.fancybox.js
    - public/javascripts/jquery.fileupload.js
    - public/javascripts/jquery.fileupload-ui.js
    - public/javascripts/ajaxupload.js
    - public/javascripts/jquery.pnotify.js
    - public/javascripts/jquery-validate.js
    - public/javascripts/jquery.metadata.js
    - public/javascripts/jquery.autogeocomplete.js
  student_lounge:
    - public/javascripts/jquery.js
    - public/javascripts/rails.js
    - public/javascripts/app.js
    - public/javascripts/swfobject.js
    - public/javascripts/jquery-ui.js
    - public/javascripts/jquery.mcdropdown.js
    - public/javascripts/jquery.bgiframe.js
    - public/javascripts/jquery-auto-suggest.js
    - public/javascripts/jquery-wysiwyg.js
    - public/javascripts/jquery-jeditable.js
    - public/javascripts/jquery-carrousel.js
    - public/javascripts/jquery-swfobject.js
    - public/javascripts/jquery-customWindow.js
    - public/javascripts/thickbox.js
    - public/javascripts/vtip.js
    - public/javascripts/json.js
    - public/javascripts/jquery-galleriffic.js
    - public/javascripts/jquery-opacityrollover.js
    - public/javascripts/swfupload.js
    - public/javascripts/swfupload-handlers.js
    - public/javascripts/jquery.ad-gallery.js
    - public/javascripts/checkboxmenu.js
    - public/javascripts/drplayer.js
    - public/javascripts/jquery.jqpageflow.js
    - public/javascripts/jquery.fancybox.js
    - public/javascripts/jquery.fileupload.js
    - public/javascripts/jquery.fileupload-ui.js
    - public/javascripts/ajaxupload.js
    - public/javascripts/jquery.pnotify.js
    - public/javascripts/jquery-validate.js
    - public/javascripts/jquery.metadata.js
    - public/javascripts/jquery.autogeocomplete.js
  admin:
    - public/javascripts/jquery.js
    - public/javascripts/jquery-ui.js
    - public/javascripts/jquery.mcdropdown.js
    - public/javascripts/jquery.bgiframe.js
    - public/javascripts/thickbox.js
    - public/javascripts/vtip.js
    - public/javascripts/custom-jquery.js
    - public/javascripts/date.js
    - public/javascripts/jquery-bind.js
    - public/javascripts/jquery-dimensions.js
    - public/javascripts/jquery-datePicker.js
    - public/javascripts/jquery-filestyle.js
    - public/javascripts/jquery-tooltip.js
    - public/javascripts/jquery-usermode.js
    - public/javascripts/ui-checkbox.js
    - public/javascripts/jquery-multiselect.js
    - public/javascripts/rails.js
    - public/javascripts/app.js
    - public/javascripts/jquery-validate.js
    - public/javascripts/jquery.metadata.js
stylesheets:
  base:
    - public/stylesheets/main.css
    - public/stylesheets/post.css
    - public/stylesheets/jquery-ui.css
    - public/stylesheets/jquery-ui-theme.css
    - public/stylesheets/jquery-ui-button.css
    - public/stylesheets/jquery-ui-resizable.css
    - public/stylesheets/jquery-ui-datepicker.css
    - public/stylesheets/jquery-ui-dialog.css
    - public/stylesheets/jquery-mcdropdown.css
    - public/stylesheets/jquery-multiSelect.css
    - public/stylesheets/jquery-auto-suggest.css
    - public/stylesheets/pagination.css
    - public/stylesheets/validation.css
    - public/stylesheets/flash.css
    - public/stylesheets/vtip.css
    - public/stylesheets/thickbox.css
    - public/stylesheets/jquery-wysiwyg.css
    - public/stylesheets/tag.css
    - public/stylesheets/footer-menu.css
    - public/stylesheets/jquery.fileupload-ui.css
    - public/stylesheets/checkboxmenu.css
    - public/stylesheets/jquery.fancybox.css
    - public/stylesheets/jquery.pnotify.default.css
    - public/stylesheets/jquery.autogeocomplete.css
  student_lounge:
    - public/stylesheets/main.css
    - public/stylesheets/post.css
    - public/stylesheets/student-lounge.css
    - public/stylesheets/jquery-ui.css
    - public/stylesheets/jquery-ui-theme.css
    - public/stylesheets/jquery-ui-button.css
    - public/stylesheets/jquery-ui-resizable.css
    - public/stylesheets/jquery-ui-datepicker.css
    - public/stylesheets/jquery-ui-dialog.css
    - public/stylesheets/jquery-mcdropdown.css
    - public/stylesheets/jquery-auto-suggest.css
    - public/stylesheets/jquery-customWindow.css
    - public/stylesheets/pagination.css
    - public/stylesheets/validation.css
    - public/stylesheets/flash.css
    - public/stylesheets/vtip.css
    - public/stylesheets/thickbox.css
    - public/stylesheets/jquery-wysiwyg.css
    - public/stylesheets/tag.css
    - public/stylesheets/jquery-carrousel.css
    - public/stylesheets/footer-menu.css
    - public/stylesheets/swfupload.css
    - public/stylesheets/jquery.ad-gallery.css
    - public/stylesheets/jquery.fileupload-ui.css
    - public/stylesheets/checkboxmenu.css
    - public/stylesheets/jqpageflow.css
    - public/stylesheets/jquery.fancybox.css
    - public/stylesheets/jquery.pnotify.default.css
  admin:
    - public/stylesheets/main.css
    - public/stylesheets/jquery-multiSelect.css
    - public/stylesheets/admin-datePicker.css
    - public/stylesheets/admin-pro-dropline.css
    - public/stylesheets/admin-pro-dropline-ie.css
    - public/stylesheets/admin-screen.css
    - public/stylesheets/thickbox.css
    - public/stylesheets/post.css
    - public/stylesheets/jquery-mcdropdown.css
