---
javascripts:
- base:
  - jquery
  - rails
  - application
  - swfobject
  - jquery-ui
  - jquery-mcdropdown
  - jquery-auto-suggest
  - jquery-validate
  - jquery-counter
  - jquery-multiselect
  - jquery-wysiwyg
  - jquery-swfobject
  - thickbox
  - vtip-min
  - tag
  - json
  - jquery-opacityrollover
  - jquery-gmap
  - checkboxmenu
  - drplayer
  - jquery.fileupload
  - jquery.fileupload-ui
  - ajaxupload
- student_lounge:
  - jquery
  - rails
  - app
  - swfobject
  - jquery-ui
  - jquery-mcdropdown
  - jquery-auto-suggest
  - jquery-validate
  - jquery-wysiwyg
  - jquery-jeditable
  - jquery-carrousel
  - jquery-swfobject
  - jquery-customWindow
  - thickbox
  - vtip-min
  - tag
  - json
  - jquery-galleriffic
  - jquery-opacityrollover
  - swfupload
  - swfupload-handlers
  - jquery.ad-gallery
  - checkboxmenu
  - drplayer
  - jquery.jqpageflow
  - jquery.fancybox
  - jquery.fileupload
  - jquery.fileupload-ui
  - ajaxupload
- admin:
  - jquery
  - jquery-ui
  - jquery-mcdropdown
  - thickbox
  - jquery-validate
  - vtip-min
  - custom-jquery
  - date
  - jquery-bind
  - jquery-dimensions
  - jquery-datePicker
  - jquery-filestyle
  - jquery-tooltip
  - jquery-usermode
  - ui-checkbox
  - jquery-multiselect
  - rails
  - app
stylesheets:
- base:
  - main
  - post
  - jquery-ui
  - jquery-ui-theme
  - jquery-ui-button
  - jquery-ui-resizable
  - jquery-ui-datepicker
  - jquery-ui-dialog
  - jquery-mcdropdown
  - jquery-multiSelect
  - jquery-auto-suggest
  - pagination
  - validation
  - flash
  - vtip
  - thickbox
  - jquery-wysiwyg
  - tag
  - footer-menu
  - jquery.fileupload-ui
  - checkboxmenu
- student_lounge:
  - main
  - post
  - student-lounge
  - jquery-ui
  - jquery-ui-theme
  - jquery-ui-button
  - jquery-ui-resizable
  - jquery-ui-datepicker
  - jquery-ui-dialog
  - jquery-mcdropdown
  - jquery-auto-suggest
  - jquery-customWindow
  - pagination
  - validation
  - flash
  - vtip
  - thickbox
  - jquery-wysiwyg
  - tag
  - jquery-carrousel
  - footer-menu
  - swfupload
  - jquery.ad-gallery
  - jquery.fileupload-ui
  - checkboxmenu
  - jqpageflow
  - jquery.fancybox
- admin:
  - main
  - admin-datePicker
  - admin-pro-dropline
  - admin-pro-dropline-ie
  - admin-screen
  - thickbox
  - post
  - jquery-mcdropdown
