--- 
javascripts: 
- application:
  - application
  - jquery
  - jquery-ui
  - jquery-ui-widget
  - jquery-ui-mouse
  - jquery-ui-draggable
  - jquery-ui-position
  - jquery-ui-resizable
  - jquery-ui-button
  - jquery-ui-datepicker
  - jquery-ui-dialog
  - jrails
  - jquery-mcdropdown
  - jquery-auto-suggest
  - thickbox
  - jquery-validate
  - jquery-counter
  - jquery-multiselect
  - vtip-min
  - jquery-wysiwyg
- student_lounge:
  - application
  - jquery
  - jquery-ui
  - jquery-ui-widget
  - jquery-ui-mouse
  - jquery-ui-draggable
  - jquery-ui-position
  - jquery-ui-resizable
  - jquery-ui-button
  - jquery-ui-datepicker
  - jquery-ui-dialog
  - jquery-auto-suggest
  - jrails
  - jquery-mcdropdown
  - thickbox
  - jquery-validate
  - vtip-min
  - jquery-wysiwyg
- admin:
  - application
  - jquery
  - jquery-ui
  - jquery-ui-datepicker
  - jrails
  - jquery-mcdropdown
  - thickbox
  - jquery-validate
  - vtip-min
stylesheets: 
- application:
  - main
  - post
  - jquery-ui
  - jquery-ui-theme
  - jquery-ui-button
  - jquery-ui-resizable
  - jquery-ui-datepicker
  - jquery-ui-dialog
  - jquery-mcdropdown
  - jquery-multiselect
  - jquery-auto-suggest
  - pagination
  - validation
  - flash
  - vtip
  - thickbox
  - jquery-wysiwyg
- student_lounge:
  - main
<<<<<<< HEAD:config/asset_packages.yml
  - student-lounge
=======
  - post
  - student_lounge
>>>>>>> cf0d096bc17847ed28632312a87811aeed5a5d41:config/asset_packages.yml
  - jquery-ui
  - jquery-ui-theme
  - jquery-ui-button
  - jquery-ui-resizable
  - jquery-ui-datepicker
  - jquery-ui-dialog
  - jquery-mcdropdown
  - jquery-auto-suggest
  - pagination
  - validation
  - flash
  - vtip
  - thickbox
  - jquery-wysiwyg
- admin:
  - main