--- 
javascripts: 
- application:
  - prototype
  - effects
  - dragdrop
  - controls
  - application
  - validation
  - dialog
- student_louge:
  - prototype
  - effects
  - dragdrop
  - controls
  - application
  - mydows
- admin:
  - prototype
  - effects
  - dragdrop
  - controls
  - application
  - validation
  - lowpro
  - frontend
  - prototip
stylesheets: 
- application:
  - main
  - pagination
  - validation
  - sexy_flash
  - dialog
- student_louge:
  - reset
  - layout
  - style
  - buttons
  - search
  - pagination
  - windows
  - account
  - listing
  - posting
  - default
- admin:
  - admin_reset
  - admin_layout
  - admin_style
  - admin_icons
  - pagination
  - prototip
  - windows
  - listing
  - posting
  - buttons
  - search