--- 
javascripts: 
- application:
  - application
  - jquery
  - jquery-ui
  - jrails
  - jquery-mcdropdown
  - jquery-auto-suggest
  - thickbox
  - jquery-validate
  - jquery-counter
  - jquery-multiselect
  - vtip-min
  - jquery-wysiwyg
  - tag
- student_lounge:
  - application
  - jquery
  - jquery-ui
  - jquery-auto-suggest
  - jrails
  - jquery-mcdropdown
  - thickbox
  - jquery-validate
  - vtip-min
  - jquery-wysiwyg
  - ajaxupload
  - tag
  - jquery-jeditable
  - jquery-carrousel
  - jquery-swfobject
  - jquery-jwplayer
- admin:
  - application
  - jquery
  - jquery-ui
  - jquery-ui-datepicker
  - jrails
  - jquery-mcdropdown
  - thickbox
  - jquery-validate
  - vtip-min
stylesheets: 
- application:
  - main
  - post
  - jquery-ui
  - jquery-ui-theme
  - jquery-ui-button
  - jquery-ui-resizable
  - jquery-ui-datepicker
  - jquery-ui-dialog
  - jquery-mcdropdown
  - jquery-multiselect
  - jquery-auto-suggest
  - pagination
  - validation
  - flash
  - vtip
  - thickbox
  - jquery-wysiwyg
  - tag
- student_lounge:
  - main
  - post
  - student-lounge
  - jquery-ui
  - jquery-ui-theme
  - jquery-ui-button
  - jquery-ui-resizable
  - jquery-ui-datepicker
  - jquery-ui-dialog
  - jquery-mcdropdown
  - jquery-auto-suggest
  - pagination
  - validation
  - flash
  - vtip
  - thickbox
  - jquery-wysiwyg
  - tag
  - jquery-carrousel
- admin:
  - main