# Configuration options can be accessed as
#   configatron.site_name

development: &local
    site_name: AfterClassroom
    site_url: http://afterclassroom.com
    
    company_name: AfterClassroom
    admin_email: admin@afterclassroom.com
    
    support_name: Support
    support_email: support@afterclassroom.com

    # Alert
    str_rated: You have rated this.

production:
  <<: *local
  
staging:
  <<: *local

test:
  <<: *local
