development:
    server: smtp.gmail.com
    port: 587
    domain: wheeree.com
    authentication: plain
    username: dungtqa@wheeree.com
    password: dungtqa990478
production:
    server: smtp.gmail.com
    port: 587
    domain: wheeree.com
    authentication: plain
    username: dungtqa@wheeree.com
    password: dungtqa990478
    tls: true