development:
  server: smtp.gmail.com
  port: 587
  domain: afterclassroom.com
  authentication: plain
  username: technical@afterclassroom.com
  password: huyettam2011
production:
  server: smtp.gmail.com
  port: 587
  domain: afterclassroom.com
  authentication: plain
  username: technical@afterclassroom.com
  password: huyettam2011
  tls: true