development:
  server: smtp.gmail.com
  port: 587
  domain: afterclassroom.com
  authentication: plain
  username: register@afterclassroom.com
  password: vietnam0101
production:
  server: smtp.gmail.com
  port: 587
  domain: afterclassroom.com
  authentication: plain
  username: register@afterclassroom.com
  password: vietnam0101
  tls: true