development:
  server: mail.coderomail.com
  port: 25
  domain: coderomail.com
  authentication: login
  username: signup
  password: huyettam2010
production:
  server: mail.coderomail.com
  port: 25
  domain: coderomail.com
  authentication: login
  username: signup
  password: huyettam2010
  tls: true