---
javascripts: 
  application:
  - application
  - jquery
  - jquery-ui
  - jrails
  - jquery-mcdropdown
  - jquery-auto-suggest
  - jquery-validate
  - jquery-counter
  - jquery-multiselect
  - jquery-wysiwyg
  - thickbox
  - vtip-min
  - tag
  - json
  - jquery-galleriffic
  - jquery-opacityrollover
  - jquery-gmap
  student_lounge:
  - application
  - jquery
  - jquery-ui
  - jrails
  - jquery-mcdropdown
  - jquery-auto-suggest
  - jquery-validate
  - jquery-wysiwyg
  - jquery-jeditable
  - jquery-carrousel
  - jquery-swfobject
  - jquery-customWindow
  - thickbox
  - vtip-min
  - ajaxupload
  - tag
  - json
  - jquery-galleriffic
  - jquery-opacityrollover
  - swfupload
  - swfupload-handlers
  - jquery.ad-gallery
  admin:
  - jquery
  - jquery-ui
  - jrails
  - jquery-mcdropdown
  - thickbox
  - jquery-validate
  - vtip-min
  - custom-jquery
  - date
  - jquery-bind
  - jquery-dimensions
  - jquery-datePicker
  - jquery-filestyle
  - jquery-pngFix-pack
  - jquery-selectbox-0.5
  - jquery-selectbox-0.5-style-2
  - jquery-selectbox-0.5-style-3
  - jquery-tooltip
  - jquery-usermode
  - ui-checkbox
  - jquery-multiselect
stylesheets: 
  application:
  - main
  - post
  - jquery-ui
  - jquery-ui-theme
  - jquery-ui-button
  - jquery-ui-resizable
  - jquery-ui-datepicker
  - jquery-ui-dialog
  - jquery-mcdropdown
  - jquery-multiSelect
  - jquery-auto-suggest
  - pagination
  - validation
  - flash
  - vtip
  - thickbox
  - jquery-wysiwyg
  - tag
  - footer-menu
  student_lounge:
  - main
  - post
  - student-lounge
  - jquery-ui
  - jquery-ui-theme
  - jquery-ui-button
  - jquery-ui-resizable
  - jquery-ui-datepicker
  - jquery-ui-dialog
  - jquery-mcdropdown
  - jquery-auto-suggest
  - jquery-customWindow
  - pagination
  - validation
  - flash
  - vtip
  - thickbox
  - jquery-wysiwyg
  - tag
  - jquery-carrousel
  - footer-menu
  - swfupload
  - jquery.ad-gallery
  admin:
  - main
  - admin-datePicker
  - admin-pro-dropline
  - admin-pro-dropline-ie
  - admin-screen
  - jquery-multiSelect
  