---
javascripts: 
  application:
  - application
  - jquery
  - jquery-ui
  - jrails
  - jquery-mcdropdown
  - jquery-auto-suggest
  - jquery-validate
  - jquery-counter
  - jquery-multiselect
  - jquery-wysiwyg
  - thickbox
  - vtip-min
  - tag
  - json
  - jquery-galleriffic
  - jquery-opacityrollover
  - jquery-gmap
  student_lounge:
  - application
  - jquery
  - jquery-ui
  - jrails
  - jquery-mcdropdown
  - jquery-auto-suggest
  - jquery-validate
  - jquery-wysiwyg
  - jquery-jeditable
  - jquery-carrousel
  - jquery-swfobject
  - jquery-customWindow
  - thickbox
  - vtip-min
  - ajaxupload
  - tag
  - json
  - jquery-galleriffic
  - jquery-opacityrollover
  - swfupload
  - swfupload-handlers
  admin:
  - application
  - jquery
  - jquery-ui
  - jrails
  - jquery-mcdropdown
  - thickbox
  - jquery-validate
  - vtip-min
stylesheets: 
  application:
  - main
  - post
  - jquery-ui
  - jquery-ui-theme
  - jquery-ui-button
  - jquery-ui-resizable
  - jquery-ui-datepicker
  - jquery-ui-dialog
  - jquery-mcdropdown
  - jquery-multiSelect
  - jquery-auto-suggest
  - pagination
  - validation
  - flash
  - vtip
  - thickbox
  - jquery-wysiwyg
  - tag
  - footer-menu
  student_lounge:
  - main
  - post
  - student-lounge
  - jquery-ui
  - jquery-ui-theme
  - jquery-ui-button
  - jquery-ui-resizable
  - jquery-ui-datepicker
  - jquery-ui-dialog
  - jquery-mcdropdown
  - jquery-auto-suggest
  - jquery-customWindow
  - pagination
  - validation
  - flash
  - vtip
  - thickbox
  - jquery-wysiwyg
  - tag
  - jquery-carrousel
  - footer-menu
  - swfupload
  admin:
  - main
  - admin_datePicker
  - admin_pro_dropline
  - admin_pro_dropline_ie
  - admin_screen