production:
  port: 3312
  address: 127.0.0.1
  mem_limit: 512M
  max_children: 300
  max_matches: 100000
  seamless_rotate: 1
  preopen_indexes: 1
  query_log_file: /mnt/app/rails/releases/code/log/searchd.query.log
  searchd_log_file: /mnt/app/rails/releases/code/log/searchd.log
  pid_file: /mnt/app/crawler/rails/code/log/searchd.production.pid
  searchd_file_path: /mnt/app/rails/current/db/sphinx/production/