developer_tag: your_developer_tag
auth_sub:
  secure: 0
  session: 1
  developer_key: AI39si6K0kaEhGv-TiOJYhxW-vkaLoNTIjlFjfF-o966FhQwwYedCAdEywZYvATHX9U6EEO8MBS_RWvNfplI_wluyFaTXKrz3A
  client_key: www.afterclassroom.com