developer_tag: your_developer_tag
auth_sub:
  secure: 0
  session: 1
  developer_key: AI39si6D4NA-q7LxRMitayFzL5SgMZX_Aa-DMx-pTMzyRyeyNUsfjG0Y0W3gtTjdzJc8YJtbg2tan6f7Col-iwokZXgEWehAxQ
  client_key: afterclassroom